### ISSUE TITLE
NFS Ganesha, FSAL, file corruption on master fail-over

### ISSUE THREAD

**Issue by LukasK32** [leil-io/saunafs#68]
Behavior of NFS Ganesha with SaunaFS FSAL on SaunaFS Master fail-over is flaky and sometimes files in-flight are corrupted.

## Software versions
OS: `Ubuntu 22.04LTS`
SaunaFS Version: `4.0.1-20240301-164017-stable-main-82161d4f` (from SaunaFS repositories)
Ganesha Version: `4.3-1` (from lunar repositories)

## Setup
For easy reproduction, steps are performed on a single machine with SaunaFS Master, Chunkserver and NFS Ganesha. Master failover are simulated by restarting the service.

Configuration files:

* `/etc/saunafs/sfsmaster.cfg`

    ```cfg
    PERSONALITY = master
    MASTER_HOST = sfsmaster
    MASTER_PORT = 9419
    MASTER_TIMEOUT = 10
    AUTO_RECOVERY = 1
    REJECT_OLD_CLIENTS = 1
    AVOID_SAME_IP_CHUNKSERVERS = 1
    MATOCS_LISTEN_HOST = *
    MATOCS_LISTEN_PORT = 9420
    MATOCL_LISTEN_HOST = *
    MATOCL_LISTEN_PORT = 9421
    OPERATIONS_DELAY_DISCONNECT = 300
    ```

* `/etc/saunafs/sfsexports.cfg`

    ```cfg
    *                       /       rw,alldirs,maproot=0,ignoregid
    *                       .       rw
    ```

* `/etc/saunafs/sfsgoals.cfg`

    ```cfg
    1 1 : _
    2 2 : _ _
    3 3 : _ _ _
    4 4 : _ _ _ _
    5 5 : _ _ _ _ _
    10 ec21 : $ec(2,1)
    11 ec31 : $ec(3,1)
    12 ec32 : $ec(3,2)
    ```

* `/etc/saunafs/sfschunkserver.cfg`

    ```cfg
    MASTER_HOST = 10.20.32.159
    HDD_LEAVE_SPACE_DEFAULT = 2GB
    ```

* `/etc/saunafs/sfshdd.cfg`

    ```cfg
    /var/lib/saunafs-chunks
    ```

* `/etc/ganesha/ganesha.conf`

    ```conf
    EXPORT
    {
        Export_Id = 77;
        Path = "/";
        Pseudo = "/";
        Access_Type = RW;
        Squash = None;
        Attr_Expiration_Time = 0;

        FSAL {
            Name = SaunaFS;
            hostname = "10.20.32.159";
            port = "9421";
            io_retries = 5;
            cache_expiration_time_ms = 2500;
        }

        Protocols = 3, 4;
    }
    ```

## Reproduction steps
These steps are flaky, sometimes the file is sent correctly, sometimes it hangs indefinitely, sometimes it finishes with corrupted file.

```sh
# Mount using both SaunsFS Client and NFS
$ mkdir -p /mnt/{saunafs,nfs}
$ sfsmount /mnt/saunafs
$ mount -vvvv 10.20.32.159:/ /mnt/nfs

# Create a file for testing with checksum
$ head -c 3G /dev/random | pv > /mnt/test_file

# Upload the file using NFS while killing the master every ten seconds
$ while true; do sleep 10 && systemctl restart saunafs-master.service; done &
$ MASTER_KILL_PID=$!
$ pv /mnt/test_file > /mnt/nfs/test_file
$ kill $MASTER_KILL_PID

# Verify checksums
$ sha256sum /mnt/{,saunafs,nfs}/test_file
```

**Comment by uristdwarf** [comment]
@ralcolea You probably might have a better idea on what's going on, since you were working on Ganesha

**Comment by ralcolea** [comment]
Yes, sure. I will take a look asap.

**Comment by ralcolea** [comment]
For addressing this issue, I have been working in two tests: the first one to validate there is no file corruption in data, and the second to prove that NFS mount can become unavailable during master failover.

I created PR #91 with the first test. This test proves that NFS client sometimes takes longer to recover from failover situations.

The second test was not included in PR #91 because the test is not deterministic in different runs: sometimes the test passes when NFS mount becomes unavailable, and sometimes the test fails when NFS is available all the time. I really appreciate the notification about this bug, because so far, we didn't have this kind of tests and they are very useful to continue improving SaunaFS.

**Comment by ralcolea** [comment]
Hi @LukasK32,

Thank you for your feedback. You're right, the final test is not exactly the same from your report, despite being used as a reference. One change was not using kill for the master, and instead using restart, because even if it's available, after killing the master, restart command in the subshell was not able to bring back master again, or at least I couldn't find a way to do it.

The use of `cp` at the end was only to avoid adding new dependences like `pv` in this case. However, `pv` also works, because in every case, it's checked that the mount is available. 

Summarizing, the test fails when a read/write operation is requested and NFS mount is not available due to the master restart. Before validating availability of NFS mount, the tests failed sometimes no matter the tool used for copying (`cp`, `pv`).

Anyways, I will try again to see if I can reproduce a new test closer to the one you reported and see how it works. I will keep you posted about it :)

**Comment by ralcolea** [comment]
Hi @LukasK32,

I have been working in this issue. I added a new test that allowed me reproduce sometimes the original issue. The test was pushed to [ganesha-issue-68](https://github.com/leil-io/saunafs/commit/4090d2acd2ed1ae262ce6e092160f24e5b0bc38d) branch.

In the original, I was able to reproduce the issue only sometimes, because as you mention, is not deterministic. I also tuned `retrans` and `timeo` parameters of nfs client. However, it didn't change the results.

The significant change I did, and after which I have not been able to reproduce the issue again, was to set `Lease_Lifetime` and `Grace_Period` parameters with correct values. These values were incorrectly configured according to Ganesha documentation.

`Lease_Lifetime` value was set to 3 seconds and `Grace_Period` was set to 5 seconds. According to the documentation, it is not recommended and it can impact in preventing data corruption. 

I think the new test is closer to the original report you did. Anyways, please give me your feedback about it.

I'm not saying this is the final solution, is still under test. However, it definitely modifies the behaviour of the test compared with the one with the wrong parameters and is the right way.

Before changing both values, I repeated the test 5 times and very often failed at least once. After updating the values of these parameters, I have not been able to reproduce the issue again. Below, I let you a brief description of these two parameters.


### Grace Period (`Grace_Period`)

- **Purpose**: The grace period is a time window following the startup of the NFS server during which only clients that are reclaiming state (like locks or leases) are allowed to perform stateful operations. This period allows clients to reclaim their locks and other stateful resources without interference from other clients attempting to establish new locks or sessions.
- **Typical Use**: It's used after server restarts or recoveries to ensure that clients have a chance to reclaim their previous state, preventing data corruption or access conflicts.

### Lease Lifetime (`Lease_Lifetime`)

- **Purpose**: The lease lifetime is the duration for which the server guarantees the validity of a client's lock or session state without needing a renewal. If a client does not renew its lease within this time, the server may reclaim the resources and assign them to other clients.
- **Typical Use**: It's used to manage the duration of client state (like locks) on the server, ensuring that unresponsive or disconnected clients do not indefinitely hold resources.

### Relationship

- **Grace Period vs. Lease Lifetime**: The grace period should logically be shorter than or at most equal to the lease lifetime. This ensures that any client that was active before the server restart has a chance to reclaim its state before the lease lifetime expires, preventing the server from reclaiming the locks or state that might still be considered valid by the client.
- **Configuration Consideration**: When configuring these parameters, it's important to balance the need for quick recovery and resource reclamation (`Lease_Lifetime`) against the need to give clients enough time to reclaim their state after a server restart (`Grace_Period`). A too-short grace period might not give clients enough time to reconnect and reclaim their state, especially in environments with network latency or when clients are spread across different geographies. On the other hand, a too-long lease lifetime might delay the reclamation of resources from unresponsive clients, potentially leading to resource exhaustion.

**Comment by LukasK32** [comment]
Hello,

I tested it again with your config and newest releases of both SaunaFS and Ganesha (from Lunar repositories) and I could not reproduce the issue anymore so I think it's fixed, thank you :)

**Comment by ralcolea** [comment]
Thank you very much @LukasK32 for your feedback.
I'm happy that the issue was fixed :)
It's a pleasure to work with your team and contribute to make our products better!!
