### ISSUE TITLE
recursive_remove.cc: fail to build

### ISSUE THREAD

**Issue by lurdan** [leil-io/saunafs#70]
I'm trying to build for arm64 (in docker, ubuntu jammy), but getting the following error:

> /tmp/saunafs_deb_working_directory.2024-05-07_143835.1Z3oVs/saunafs/src/tools/recursive_remove.cc: In function 'int recursive_remove_run(int, char**)':
> /tmp/saunafs_deb_working_directory.2024-05-07_143835.1Z3oVs/saunafs/src/tools/recursive_remove.cc:129:47: error: comparison is always true due to limited range of data type [-Werror=type-limits]
>   129 |         while ((ch = getopt(argc, argv, "l")) != -1) {
>       |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
> cc1plus: all warnings being treated as errors

It seems that the issue is not related to the architecture, but rather that `ch` is unsigned.

**Comment by lurdan** [comment]
I found the cause. On arm64, an implicit char is unsigned (whereas on x86 it is signed).

Since I'm assuming the arm architecture is out of your scope, I will close this.

**Comment by uristdwarf** [comment]
> I found the cause. On arm64, an implicit char is unsigned (whereas on x86 it is signed).
> Since I'm assuming the arm architecture is out of your scope, I will close this.

While it's true that ARM64 is a low priority for us, that doesn't mean we don't want to improve it.

We checked yesterday and found the same exact issue (char is unsigned on arm, versus signed on x86). Everywhere else it uses int but in this specific instance it's using char for some reason. It compiles everything when it's changed to int.

We know ARM64 has definitive problems, especially regarding performance. So we would be happy if people who use ARM can continue reporting issues like these, especially because we are focused on X86.

I would even accept PR's for improvement regarding ARM64, otherwise I think we can fix this particular issue in a few days in the `dev` branch.

**Comment by lurdan** [comment]
Thanks, I'm happy to hear that!

**Comment by uristdwarf** [comment]
Fixed in dev branch
